"""update products table with Cloudinary + JSONB

Revision ID: 627ad06c919b
Revises: dab6a3a5d49b
Create Date: 2025-09-17 23:28:13.224991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627ad06c919b'
down_revision = 'dab6a3a5d49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    # ### end Alembic commands ###
