"""Add status to contact messages

Revision ID: dab6a3a5d49b
Revises: a46fa03d96cd
Create Date: 2025-09-16 13:45:12.039683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab6a3a5d49b'
down_revision = 'a46fa03d96cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
